version: "3.2"

services:
  api-auth-verify-token:
    image: api-auth-token-generator
    build:
      context: ApiAuthVerifyToken/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=entitycorex;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  api-auth-verify-token-test: &api-auth-verify-token-test
    image: api-auth-token-generator-test
    build:
      context: .
      dockerfile: ApiAuthVerifyToken.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - test-database
      - dynamodb-database

  api-auth-verify-token-test-new:
    << : *api-auth-verify-token-test
    build:
      context: .
      dockerfile: ApiAuthVerifyTokenNew.Tests/Dockerfile

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000