services:
  api-auth-verify-token:
    image: api-auth-token-generator
    build:
      context: ApiAuthVerifyToken/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=auth_token_generator_db;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  api-auth-verify-token-test:
    image: api-auth-token-generator-test
    build:
      context: .
      dockerfile: ApiAuthVerifyToken.Tests/Dockerfile
    links:
      - test-database
      - dynamodb-database

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env

  dynamodb-database:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb" # Expose the shared database
    ports:
      - 8000:8000
  
  # DynamoDB Admin UI for inspecting the local DynamoDB
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-database:8000"
      AWS_REGION: "eu-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-database