create table api_lookup
(
    id             integer generated by default as identity
        unique,
    api_name       varchar(255) not null,
    api_gateway_id varchar(16)
);

create table api_endpoint_lookup
(
    id            integer generated by default as identity
        unique,
    api_lookup_id integer
        references api_lookup (id),
    endpoint_name varchar(255)
);

create table consumer_type_lookup
(
    id            integer generated by default as identity
        unique,
    consumer_name varchar(255)
);

create table tokens
(
    id                     serial
        primary key,
    api_lookup_id          integer
        references api_lookup (id),
    api_endpoint_lookup_id integer
        references api_endpoint_lookup (id),
    http_method_type       varchar(6),
    environment            varchar(255),
    consumer_name          varchar(255),
    consumer_type_lookup   integer
        references consumer_type_lookup (id),
    requested_by           varchar(255),
    authorized_by          varchar(255),
    date_created           timestamp not null,
    expiration_date        timestamp,
    enabled                boolean   not null
);

create index "IX_tokens_api_endpoint_lookup_id"
    on tokens (api_endpoint_lookup_id);

create index "IX_tokens_api_lookup_id"
    on tokens (api_lookup_id);

create index "IX_tokens_consumer_type_lookup"
    on tokens (consumer_type_lookup);
