create table api_lookup
(
    id             integer generated by default as identity
        constraint "PK_api_lookup"
            primary key,
    api_name       text not null,
);

create table api_endpoint_lookup
(
    id            integer generated by default as identity
        constraint "PK_api_endpoint_lookup"
            primary key,
    endpoint_name text    not null,
    api_lookup_id integer not null
);

create table consumer_type_lookup
(
    id            integer generated by default as identity
        constraint "PK_consumer_type_lookup"
            primary key,
    consumer_name text not null
);

create table tokens
(
    id                     integer generated by default as identity
        constraint "PK_tokens"
            primary key,
    api_lookup_id          integer    not null
        -- constraint "FK_tokens_api_lookup_api_lookup_id"
        --     references api_lookup
        --     on delete cascade,
    api_endpoint_lookup_id integer    not null
        -- constraint "FK_tokens_api_endpoint_lookup_api_endpoint_lookup_id"
        --     references api_endpoint_lookup
        --     on delete cascade,
    http_method_type       varchar(6) not null,
    environment            text       not null,
    consumer_name          text       not null,
    consumer_type_lookup   integer    not null
        -- constraint "FK_tokens_consumer_type_lookup_consumer_type_lookup"
        --     references consumer_type_lookup
        --     on delete cascade,
    requested_by           text       not null,
    authorized_by          text       not null,
    date_created           timestamp  not null,
    expiration_date        timestamp,
    enabled                boolean    not null
);

create index "IX_tokens_api_endpoint_lookup_id"
    on tokens (api_endpoint_lookup_id);

create index "IX_tokens_api_lookup_id"
    on tokens (api_lookup_id);

create index "IX_tokens_consumer_type_lookup"
    on tokens (consumer_type_lookup);

